---
settings:
  name: SnapCenter Service
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,zh-cn,zh-tw,ko-kr,de-de
sidebar:
  entries:
  - title: Documentation du service SnapCenter
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/whats-new.html"
  - title: Commencez
    entries:
    - title: Découvrez le service SnapCenter
      url: "/concept-overview-architecture-limitation-functionalities-snapcenter-service.html"
    - title: Démarrage rapide
      url: "/reference-get-started-snapcenter-service.html"
    - title: Conditions préalables pour créer un connecteur et activer le service
        SnapCenter
      url: "/reference-prerequisites-azure-connector-snapcenter-service.html"
    - title: Créez un connecteur dans Azure pour le service SnapCenter
      url: "/task-create-azure-connector-user-consent-snapcenter-service.html"
    - title: Activez le service SnapCenter pour Azure NetApp Files
      url: "/task-enable-snapcenter-service-azure-netapp-files.html"
    - title: Installez le client HDBSQL
      url: "/task-install-hdbsql-client-snapcenter-service.html"
  - title: Utilisez le service SnapCenter pour protéger les systèmes SAP HANA
    entries:
    - title: Ajout de systèmes SAP HANA
      url: "/task-add-sap-hana-systems-non-data-volumes-snapcenter-service.html"
    - title: Sauvegarde des systèmes SAP HANA
      url: "/task-create-backup-ondemand-policies-schedule-sap-hana.html"
    - title: Restaurez les systèmes SAP HANA
      url: "/task-restore-sap-hana-systems.html"
    - title: Gérez les opérations
      url: "/reference-manage-dashboard-monitor-notification-snapcenter-service.html"
    - title: Résoudre les problèmes
      url: "/reference-troubleshoot-solution-issue.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Commencez
    links:
    - title: Nouveautés
      url: "/whats-new.html"
    - title: Découvrez le service SnapCenter
      url: "/concept-overview-architecture-limitation-functionalities-snapcenter-service.html"
    - title: Démarrage rapide
      url: "/reference-get-started-snapcenter-service.html"
  - title: Activez le service SnapCenter
    links:
    - title: Prérequis
      url: "/reference-prerequisites-azure-connector-snapcenter-service.html"
    - title: Créer un connecteur
      url: "/task-create-azure-connector-user-consent-snapcenter-service.html"
    - title: Activez le service SnapCenter
      url: "/task-enable-snapcenter-service-azure-netapp-files.html"
    - title: Installez le client HDBSQL
      url: "/task-install-hdbsql-client-snapcenter-service.html"
  - title: Protection des systèmes SAP HANA
    links:
    - title: Ajout de systèmes SAP HANA
      url: "/task-add-sap-hana-systems-non-data-volumes-snapcenter-service.html"
    - title: Sauvegarde des systèmes SAP HANA
      url: "/task-create-backup-ondemand-policies-schedule-sap-hana.html"
    - title: Restaurez les systèmes SAP HANA
      url: "/task-restore-sap-hana-systems.html"
  - title: Soutien aux connaissances
    links:
    - title: S'inscrire pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/task-get-help.html"
  - title: Communauté sur les blogs
    links:
    - title: Communauté NetApp
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Blog Cloud Central
      url: https://cloud.netapp.com/blog
    - title: Webinaires sur le cloud
      url: https://cloud.netapp.com/events
product-family:
  name: Cloud Manager
  repo: cloud-manager-family
  sidebar_label: Toute la documentation de Cloud Manager
